---
apiVersion: v1
kind: Secret
metadata:
  name: jpdemo-wheres-teddy-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/WindTurbineInc/jpdemo-wheres-teddy-gitops
